
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-happycows-f23-5pm-1
owner: ucsb-cs156-f23
repo_name: proj-happycows-f23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2OTM1MzM0","is_bot":false,"login":"lukewli","name":""},"headRefName":"lliInstructorReportPageUI","number":20,"title":"lli - Added UI changes and tests for Instructor Report Page","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/pull/20"},{"author":{"id":"MDQ6VXNlcjcyODkzMDg0","is_bot":false,"login":"haroldmo","name":""},"headRefName":"Harold-UX-improvements-to-leaderboard-page-2","number":19,"title":"Harold ux improvements to leaderboard page 2","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/pull/19"},{"author":{"id":"MDQ6VXNlcjU1NTU2Mjk2","is_bot":false,"login":"Yashasvi-Vangala","name":"Yashasvi Vangala"},"headRefName":"yv-no-purchase-toast","number":17,"title":"Removed Sold Cow Toast","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/pull/17"}]
