
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-happycows-f23-5pm-1
owner: ucsb-cs156-f23
repo_name: proj-happycows-f23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjg3MDUzNTg3","is_bot":false,"login":"vinsonlinn","name":""},"headRefName":"VL-ChatRoom-UXUI","number":35,"title":"Vl chat room ux UI","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/pull/35"},{"author":{"id":"MDQ6VXNlcjc3NjU4OTQ3","is_bot":false,"login":"AngelG261","name":""},"headRefName":"Angel-Greetings-Improvement","number":34,"title":"Fixed opacity of the greetings card","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/pull/34"},{"author":{"id":"MDQ6VXNlcjcyODkzMDg0","is_bot":false,"login":"haroldmo","name":""},"headRefName":"Harold-Set-Default-Vals-Common-Fields-part2","number":32,"title":"DRAFT set default vals for common fields frontend","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/pull/32"}]
