
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-happycows-f23-5pm-1
owner: ucsb-cs156-f23
repo_name: proj-happycows-f23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjU1NTU2Mjk2","is_bot":false,"login":"Yashasvi-Vangala","name":"Yashasvi Vangala"},"headRefName":"Yashasvi-Vangala-patch-README","number":38,"title":"Update README.md","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/pull/38"},{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"AdminViewPlayPage-Banner-Improvement","number":37,"title":"improved the banner, now show the visiting name and commons name","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/pull/37"},{"author":{"id":"MDQ6VXNlcjcyODkzMDg0","is_bot":false,"login":"haroldmo","name":""},"headRefName":"Harold-Set-Default-Vals-Common-Fields-frontend2","number":36,"title":"Harold set default vals common fields frontend2","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/pull/36"},{"author":{"id":"MDQ6VXNlcjg3MDUzNTg3","is_bot":false,"login":"vinsonlinn","name":""},"headRefName":"VL-ChatRoom-UXUI","number":35,"title":"Vl chat room ux UI","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-1/pull/35"}]
